language: php
sudo: false

before_install:
  - phpenv config-rm xdebug.ini

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.2

install:
  composer install --prefer-dist --no-suggest --optimize-autoloader -q

script:
  - composer phpcs
